### ISSUE TITLE
login not work

### ISSUE THREAD

**Issue by n1arash** [fandoghpaas/fandogh-website#37]
login functionality not work at all.
after login if you reload the page user will logout

- go to login page
- login
- reload

**Comment by psycho-ir** [comment]
Hi @n1arash, 

Thanks for reaching us out. 
I couldn't reproduce the issue you mentioned. 
At the time being once you log into the fandogh a manual is shown to you to help you out how to use `fandogh-cli`. 

I refreshed the page several times but I still can see the exit button of top left corner. 
Could you please share a screen shot of what you face after refreshing the page?

**Comment by n1arash** [comment]
This is exactly what happen when i login and reload

![2018-09-08_20-04-25](https://user-images.githubusercontent.com/18232247/45255868-1e0cda00-b3a3-11e8-9307-0b1245a436e7.gif)

**Comment by n1arash** [comment]
this is exactly what happen when i login and reload page:

![2018-09-08_20-12-43](https://user-images.githubusercontent.com/18232247/45255917-ee120680-b3a3-11e8-89f3-ce3fb23019ca.gif)
